artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  src_URL: https://drive.google.com/file/d/1S0-inA_KSC4VEJx9IFJlAAXuveQCdQPM/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/kidneyCTscan

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pt

model_training:
  root_dir: artifacts/model_training
  trained_model_path: artifacts/model_training/model.pt

model_testing:
  mlflow_uri: https://dagshub.com/yhr0864/kidney-disease-classification-project.mlflow

  
