artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  src_URL: https://drive.google.com/file/d/1zUm_UQU1XAt1BV3oyMtidTUsQITL3qDN/view?usp=drive_link
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pt

model_training:
  root_dir: artifacts/model_training
  trained_model_path: artifacts/model_training/model.pt
  
