artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  src_URL: https://drive.google.com/file/d/1jGFKjl11IOSnhUx-HJnOsIPwxJWl3q-G/view?usp=drive_link
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pt
  
